require:
  - rubocop-erb
plugins:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-factory_bot
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'bin/setup'
    - 'config/**/*'
    - 'db/**/*'
Style/Documentation:
  Enabled: false
